#!/bin/bash

_ponies="$(perl $0.pl)"
ponies=()

if [[ ! $# == 0 ]]; then
    p=""
    for arg in "$@"; do
	p=$p$(echo "$_ponies" | grep "^$arg@")" "
    done
    _ponies=$p
fi

for _pony in $_ponies; do
    ponies+=( $_pony )
done

pony="${ponies[$RANDOM%${#ponies[@]}]}"

p=$(echo $pony | cut -d '@' -f 1)
f=$(echo $pony | cut -d '@' -f 2)
q=$(cat ./ponyquotes/$f)

echo "-f" $p $q

